"""add syllabus mappings

Revision ID: 742effa7f289
Revises: 53787c837466
Create Date: 2026-10-09 00:03:36.493778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '742effa7f289'
down_revision: Union[str, Sequence[str], None] = '53787c837466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabus_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lecture_id', sa.UUID(), nullable=False),
    sa.Column('syllabus_topic_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['syllabus_topic_id'], ['syllabus_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabus_mappings_lecture_id'), 'syllabus_mappings', ['lecture_id'], unique=False)
    op.create_index(op.f('ix_syllabus_mappings_syllabus_topic_id'), 'syllabus_mappings', ['syllabus_topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syllabus_mappings_syllabus_topic_id'), table_name='syllabus_mappings')
    op.drop_index(op.f('ix_syllabus_mappings_lecture_id'), table_name='syllabus_mappings')
    op.drop_table('syllabus_mappings')
    # ### end Alembic commands ###
